name: solar-system
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    name: Unit Testing
    services:
      mongo:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password

    #strategy:
      #matrix:
        #node-version: [18,19,20]
        #os: [ubuntu-latest, windows-latest, macos-latest]
        #exclude:
          #- node-version: 19
            #os: windows-latest
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup nodeJs version
        uses: actions/setup-node@v4
        with:
          #node-version: ${{ matrix['node-version'] }}
          node-version: 18
      - name: cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm install
      - name: unit-testing
        id: test
        run: npm test
      - name: Debug files 
        if: always()
        run: ls -R
      - name: Archive_Test_Result
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: Mocha-Test-Result-${{ matrix.node-version }}-${{ matrix.os }}
          path: test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup nodeJs version
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: cache npm dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run: npm install
      - name: code-coverage
        continue-on-error: true
        run: npm run coverage
      - name: Debug files 
        run: ls -R
      - name: Archive_Code_Coverage_Result
        uses: actions/upload-artifact@v4
        with: 
          name: Code-Coverage-Result
          path: coverage/lcov.info

  Containerization:
    name: Docker Build
    needs: [unit-testing, code-coverage]
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: GHCR login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name:  Docker build for testing
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
      - name: Docker image testing
        run: |
          docker run -d -p 3000:3000 --name solar-system-test ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          sleep 10
      - name: check /live endpoint
        id: check_live
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/live)
          if [ "$response" -ne 200 ]; then
            echo "Live endpoint is not healthy. Status code: $response"
            exit 1
          else
            echo "Live endpoint is healthy. Status code: $response"
          fi
      - name: Docker push
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
                ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
                ghcr.io/durgarao-devops/solar-system:${{ github.sha }}