name: solar-system
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup nodeJs version
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: unit-testing
        run: npm test
      - name: Debug files 
        run: ls -R
      - name: Archive_Test_Result
        uses: actions/upload-artifact@v4
        with: 
          name: Mocha Test Result
          path: test-results.xml